config/routes.rb
Rails.application.routes.draw do
  # Rails.application.routes.draw do
    root 'feeds#index'
    # authenticated :user do
    resources :feeds do
      collection do
        post :confirm
      end
    end
  
    get 'sessions/new'
    resources :sessions, only: [:new, :create, :show, :destroy]
    resources :users
    resources :favorites, only: [:create, :destroy]
    
    get 'favorites/:id', to: 'favorites#index'
    mount LetterOpenerWeb::Engine, at: "/letter_opener" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :favorites, dependent: :destroy
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :title,  presence: true, length: { in: 1..30 }
  validates :content,  presence: true, length: { in: 1..50 }
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: true
  validates :image, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 4 } ,allow_nil: true
  #allow_nil: true 編集時にパスワードが空でもUpload可能
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんのPictureをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんのPictureをお気に入り解除しました"
  end

  def index
    @favorite = current_user.favorites
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :update, :edit, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
      @favorite = current_user.favorites.find_by(feed_id: @feed.id)#binsding.irb
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params) #現在ログインしているuserのidを、blogのuser_idカラムに挿入する
    render :new if @feed.invalid?
  end

  def edit
    if @feed.user_id != current_user.id
      redirect_to feed_path, notice:"権限がありません"
    end
  end

  def create
    @feed = current_user.feeds.build(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Pictureを投稿しました！' }
        format.json { render :show, status: :created, location: @feed }
        ContactMailer.contact_mail(@feed).deliver
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Pictureを編集しました！' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Pictureを削除しました' }
      format.json { head :no_content }
    end
  end

  private

  def set_feed
      @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      # ログイン成功した場合
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :set_feed, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "プロフィールを登録しました！"
    else
      render 'new'
    end
  end
  
  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                              :image, :image_cache,:password_confirmation,:introduce)
  end

  def set_feed
    @user = User.find(params[:id])
  end
  
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to user_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<p id="notice"></p>
<h1>お気に入り</h1>
<table>
      <thead>
        <tr>
          <th>ユーザー  </th>
          <th>タイトル  </th>
          <th>Picture  </th>
          <th>内容  </th>
        </tr>
      </thead>
    <article>
      <% @favorite.each do |feed| %> 
        <tr>
          <td><%= feed.user.name %></td>
          <td><%= feed.feed.title %></td>
          <td><%= image_tag(feed.feed.image.url) %></td>
          <td><%= feed.feed.content %></td>
        </tr>
      <% end %>
    </article>
  </table>

  <%= link_to '投稿一覧へ', feeds_path %>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
    </div>

    <div class="blog">
      <%= form.label :タイトル %>
      <%= form.text_field :title %>
    </div>

    <div class="blog">
      <%= form.label :内容 %>
      <%= form.text_field :content %>
    </div>

    <div class="blog">
      <%= form.label :"Picture(image)" %>
      <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <%= form.submit '投稿する'%>
    </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>Pictureを投稿しますか？</h1>


<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <div class="picture">
    <p>タイトル:<%= @feed.title %></P>
    <p>本文:<%= @feed.content %></P>
    <p>Picture:
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.hidden_field :image_cache %></P>
  </div>
<% end %>
　

<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿する" %>
  <br>
  <br>
  <%= link_to '投稿一覧へ', feeds_path %>
<% end %>

app/views/feeds/edit.html.erb
<h1>編集</h1>
<%= render 'form', feed: @feed %>
<p><%= link_to '詳細', @feed %> |
<%= link_to '投稿一覧へ', feeds_path %></P>

app/views/feeds/index.html.erb
  <p id="notice"></p>
  <p><%= link_to '投稿する', new_feed_path %>
　<%= link_to 'お気に入り', favorite_path(@feeds) %></P>

  <table>
      <thead>
        <tr>
          <th>ユーザー  </th>
          <th>タイトル  </th>
          <th>Picture  </th>
          <th>内容  </th>
        </tr>
      </thead>
    <article>
      <% @feeds.each do |feed| %>
        <tr>
          <td><%= feed.user.name %></td>
          <td><%= feed.title %></td>
          <td><%= image_tag(feed.image.url) %></td>
          <td><%= feed.content %></td>
          <td><%= link_to '詳細', feed %></td>
          <% if logged_in? && feed.user.id == current_user.id %>
          <td><%= link_to '編集', edit_feed_path(feed) %></td>
          <td><%= link_to '削除', feed, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </article>
  </table>

app/views/feeds/new.html.erb
<% if logged_in? %>
  <h1>新規投稿</h1>
  <ul>
    <%= render 'form', feed: @feed %>
    <%= link_to '投稿一覧へ', feeds_path %>
  </ul>
<% end %>

app/views/feeds/show.html.erb
<p id="notice"></p>
<h1>投稿詳細</h1>
  <table>
    <p>ユーザー: <%= @feed.user.name %></p>
    <p>タイトル: <%= @feed.title %></p>
    <p>内容: <%= @feed.content %></p>
    <p>Picture: </p>
      <%= image_tag @feed.image.url %> 
  </table>

  <% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<br>
<%= link_to '投稿一覧へ', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <header class="header">Catgram</header>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body> 

  <footer>
    <p>運営会社　Cat 株式会社</p>
    <p>© 2015-2016 Copyright Dogs Corp.</p>
  </footer>
</html>

app/views/users/_form.html.erb
  <% if logged_in? %>
    <h1>編集</h1>
  <% else %>
    <h1>アカウント作成</h1>
  <% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
  <% end %>
      </ul>
    </div>
<% end %>

    <div class = "profile">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br>

    <%= f.label :email %>
    <br>
    <%= f.email_field :email %>
    <br>

    <%= f.label :introduce%>
    <br>
    <%= f.text_field :introduce %>
    <br>

    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br>

    <%= f.label :password_confirmation %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>

    <%= f.label :"プロフィール画像(Image)" %>
    <br>
    <%= f.file_field :image %>
    <br>
  
  <% if logged_in? %>
    <%= f.submit "プロフィールを編集する" %>
  <% else %>
    <%= f.submit "アカウントを作成する" %>
  <% end %>
    <br>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>
<%= link_to '詳細', @user %> |
<%= link_to '投稿一覧へ', feeds_path %>

app/views/users/new.html.erb
<ul>
  <%= render 'form', user: @user %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %>のプロフィール</h1>
<p>名前: <%= @user.name %></p>
<p>自己紹介: <%= @user.introduce %></p>
<p>メールアドレス: <%= @user.email %></p>
<p>プロフィール画像: </p>
  <%= image_tag @user.image.url %>
<br>

<%= link_to '投稿一覧へ', feeds_path %>
<% if logged_in? && @user.id == current_user.id %>
<%= link_to 'プロフィールを編集する', edit_user_path(@user) %> 
<% end %>